theme: jekyll-theme-minimal
show_downloads: true
# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Aquatic Catch Predictor
logo: /media/music_emotion.webp
description: Project for UCLA ECEM202A/CSM213A (Fall 2022)
